# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainAppDesign.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(901, 293)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frm_topMenu = QtWidgets.QFrame(self.centralwidget)
        self.frm_topMenu.setGeometry(QtCore.QRect(0, 0, 901, 51))
        self.frm_topMenu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_topMenu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_topMenu.setObjectName("frm_topMenu")
        self.btn_loadData = QtWidgets.QPushButton(self.frm_topMenu)
        self.btn_loadData.setGeometry(QtCore.QRect(10, 10, 93, 28))
        self.btn_loadData.setObjectName("btn_loadData")
        self.btn_train = QtWidgets.QPushButton(self.frm_topMenu)
        self.btn_train.setGeometry(QtCore.QRect(110, 10, 93, 28))
        self.btn_train.setObjectName("btn_train")
        self.btn_trainAll = QtWidgets.QPushButton(self.frm_topMenu)
        self.btn_trainAll.setGeometry(QtCore.QRect(210, 10, 93, 28))
        self.btn_trainAll.setObjectName("btn_trainAll")
        self.btn_loadSignal = QtWidgets.QPushButton(self.frm_topMenu)
        self.btn_loadSignal.setGeometry(QtCore.QRect(700, 10, 93, 28))
        self.btn_loadSignal.setObjectName("btn_loadSignal")
        self.btn_disagg = QtWidgets.QPushButton(self.frm_topMenu)
        self.btn_disagg.setGeometry(QtCore.QRect(800, 10, 93, 28))
        self.btn_disagg.setObjectName("btn_disagg")
        self.frm_signalMenu = QtWidgets.QFrame(self.centralwidget)
        self.frm_signalMenu.setGeometry(QtCore.QRect(0, 50, 371, 231))
        self.frm_signalMenu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_signalMenu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_signalMenu.setObjectName("frm_signalMenu")
        self.box_combBox = QtWidgets.QGroupBox(self.frm_signalMenu)
        self.box_combBox.setGeometry(QtCore.QRect(20, 10, 151, 201))
        self.box_combBox.setObjectName("box_combBox")
        self.cbx_app1 = QtWidgets.QCheckBox(self.box_combBox)
        self.cbx_app1.setGeometry(QtCore.QRect(10, 20, 131, 20))
        self.cbx_app1.setChecked(False)
        self.cbx_app1.setObjectName("cbx_app1")
        self.cbx_app2 = QtWidgets.QCheckBox(self.box_combBox)
        self.cbx_app2.setGeometry(QtCore.QRect(10, 40, 141, 20))
        self.cbx_app2.setObjectName("cbx_app2")
        self.cbx_app3 = QtWidgets.QCheckBox(self.box_combBox)
        self.cbx_app3.setGeometry(QtCore.QRect(10, 60, 131, 20))
        self.cbx_app3.setObjectName("cbx_app3")
        self.cbx_app4 = QtWidgets.QCheckBox(self.box_combBox)
        self.cbx_app4.setGeometry(QtCore.QRect(10, 80, 131, 20))
        self.cbx_app4.setObjectName("cbx_app4")
        self.cbx_app5 = QtWidgets.QCheckBox(self.box_combBox)
        self.cbx_app5.setGeometry(QtCore.QRect(10, 100, 131, 20))
        self.cbx_app5.setObjectName("cbx_app5")
        self.btn_addComb = QtWidgets.QPushButton(self.box_combBox)
        self.btn_addComb.setGeometry(QtCore.QRect(10, 130, 61, 28))
        self.btn_addComb.setObjectName("btn_addComb")
        self.btn_plotComb = QtWidgets.QPushButton(self.box_combBox)
        self.btn_plotComb.setGeometry(QtCore.QRect(10, 160, 61, 28))
        self.btn_plotComb.setObjectName("btn_plotComb")
        self.btn_clearComb = QtWidgets.QPushButton(self.box_combBox)
        self.btn_clearComb.setGeometry(QtCore.QRect(80, 130, 61, 28))
        self.btn_clearComb.setObjectName("btn_clearComb")
        self.lst_sigCombs = QtWidgets.QListWidget(self.frm_signalMenu)
        self.lst_sigCombs.setGeometry(QtCore.QRect(200, 20, 151, 191))
        self.lst_sigCombs.setObjectName("lst_sigCombs")
        self.frm_resultFrame = QtWidgets.QFrame(self.centralwidget)
        self.frm_resultFrame.setGeometry(QtCore.QRect(370, 50, 531, 231))
        self.frm_resultFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_resultFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_resultFrame.setObjectName("frm_resultFrame")
        self.txt_resultsText = QtWidgets.QTextEdit(self.frm_resultFrame)
        self.txt_resultsText.setGeometry(QtCore.QRect(20, 20, 491, 191))
        self.txt_resultsText.setReadOnly(True)
        self.txt_resultsText.setObjectName("txt_resultsText")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_loadData.setText(_translate("MainWindow", "Load Data"))
        self.btn_train.setText(_translate("MainWindow", "Train"))
        self.btn_trainAll.setText(_translate("MainWindow", "Train All"))
        self.btn_loadSignal.setText(_translate("MainWindow", "Load Signal"))
        self.btn_disagg.setText(_translate("MainWindow", "Disaggregate"))
        self.box_combBox.setTitle(_translate("MainWindow", "Combinations"))
        self.cbx_app1.setText(_translate("MainWindow", "App. 1 (Air Cond.)"))
        self.cbx_app2.setText(_translate("MainWindow", "App. 2 (Microwave)"))
        self.cbx_app3.setText(_translate("MainWindow", "App. 3 (Toaster)"))
        self.cbx_app4.setText(_translate("MainWindow", "App. 4 (Lamp)"))
        self.cbx_app5.setText(_translate("MainWindow", "App. 5 (AC Motor)"))
        self.btn_addComb.setText(_translate("MainWindow", "Add"))
        self.btn_plotComb.setText(_translate("MainWindow", "Plot"))
        self.btn_clearComb.setText(_translate("MainWindow", "Clear"))

